mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 172.19.73.190
    port: 1883
    keepalive: 60
  private_path: device/001
#serializer: json:dumps
#deserializer: json:loads
  account:
    username: "rbag"
    password: "rbag"
bridge:
